### PR TITLE
Use X-FORWARDED-FOR when reverse proxied

### PR DESCRIPTION
**Pull request by rubiojr**
Use the IP from the headers if the `X-FORWARDED-FOR` is present, which is usually the case when geoip is being reverse proxied, i.e. when doing TLS termination elsewhere.

Without this, geoip will try to resolve the IP address from the upstream proxy (private in a docker network for example) instead of the HTTP client (user's browser).

### CODE REVIEW

**Comment by lrstanley** [comment]
This is already [supported and built-in](https://github.com/lrstanley/geoip/blob/master/http.go#L34-L36) (`--http.trusted-proxies` can allow specific IPs to provide `X-Forwarded-For` headers, or other headers similar to `X-Forwarded-For` if that's not being used, e.g. **Cloudflare**, True-ClientIP, etc).

Note that using `X-Forwarded-For` by default is a security risk and **should not** be a default. It should only be applied when you can trust the source (i.e. explicitly allowing the proxy that is in front of GeoIP to provide such headers).

**Comment by rubiojr** [comment]
@lrstanley ah I see! I tried to use that, including wildcard `*` (`HTTP_TRUSTED_PROXIES="*"`), but geoip was dumping an error in my setup and not working. It's also challenging in my setup, as the Caddy reverse proxy is also docker hosted and has an docker internal IP that I can't control. Do you have any recommendations?

**Comment by rubiojr** [comment]
:point_up: 
```
geoip         | main.httpServer({0xfd92d0, 0xc000440480})
geoip         | 	github.com/lrstanley/geoip/http.go:35 +0x194
geoip         | main.main()
geoip         | 	github.com/lrstanley/geoip/main.go:47 +0x365
geoip         | timestamp=2022-11-07T15:29:45.146652283Z level=info message="logger initialized" arch=amd64 commit=unknown go_version=go1.19.1 name=github.com/lrstanley/geoip os=linux version=(devel)
geoip         | panic: realip: no real IP source specified (OptUseXForwardedFor, OptUseXRealIP, or OptUseTrueClientIP, OptUseCFConnectingIP)
geoip         | 
geoip         | goroutine 1 [running]:
geoip         | github.com/lrstanley/chix.UseRealIP({0x0?, 0x7f25a0?, 0xc000440c01?}, 0xc00031fa50?)
geoip         | 	github.com/lrstanley/chix@v0.0.0-20220905152744-9e3b5cbca59c/realip.go:110 +0x652
geoip         | github.com/lrstanley/chix.UseRealIPCLIOpts({0xc0004231a0?, 0x1, 0xc0004231a0?})
geoip         | 	github.com/lrstanley/chix@v0.0.0-20220905152744-9e3b5cbca59c/realip.go:83 +0x385
geoip         | main.httpServer({0xfd92d0, 0xc000440480})
geoip         | 	github.com/lrstanley/geoip/http.go:35 +0x194
geoip         | main.main()
geoip         | 	github.com/lrstanley/geoip/main.go:47 +0x365
```

**Comment by lrstanley** [comment]
Wildcard (`*`) just covers the allowlist portion, not what header it should use. You'd want to specify `*` and `x-forwarded-for` or similar.

Though note that you should not use `*`, I would rather recommend `local` which is just local-network IPs (including Docker internal IPs).

For example, for the production GeoIP instance, it's `Cloudflare -> Docker -> Traefik -> GeoIP`, and I use:

```
HTTP_TRUSTED_PROXIES=cloudflare,local
```

Which means I only trust Cloudflare IPs, local IPs, and the headers that Cloudflare supports for real-ip.

**Comment by rubiojr** [comment]
> Wildcard (*) just covers the allowlist (source IP) portion, not what header it should use. You'd want to specify * and x-forwarded-for or similar.

Thank you! this is what I was missing. Setting `HTTP_TRUSTED_PROXIES="x-forwarded-for,local"` did the trick!

**Pull request closed without merging**
